#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Sep 27, 2020 09:14:38 AM CAT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import acesso_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Toplevel1 (root)
    acesso_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    acesso_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        def Cancel():
           global root
           root.quit()

        def VerificaPass():
            if self.edt_pass.get()=="2020":
                from subprocess import call
                global root
                root.quit()
                call(["python3", "configure.py"])

            else:
                self.Label2.configure(text="Codigo Incorrecto")  
                

        top.geometry("490x309+504+117")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1, 1)
        top.title("Password")
        top.configure(background="#fff")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.204, rely=0.421, height=33, width=147)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#fff")
        self.Label1.configure(font="-family {DejaVu Sans} -size 12 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label1.configure(text='''Palavra Chave''')

        self.edt_pass = tk.Entry(top)
        self.edt_pass.place(relx=0.224, rely=0.518,height=21, relwidth=0.584)
        self.edt_pass.configure(background="white")
        self.edt_pass.configure(font="TkFixedFont")
        self.edt_pass.configure(selectbackground="blue")
        self.edt_pass.configure(selectforeground="white")
        self.edt_pass.focus_set()
        self.edt_pass.configure(show="*")

        self.btn_entrypass = tk.Button(top)
        self.btn_entrypass.place(relx=0.284, rely=0.693, height=29, width=66)
        self.btn_entrypass.configure(activebackground="#f9f9f9")
        self.btn_entrypass.configure(text='''Entrar''')
        self.btn_entrypass.configure(command = VerificaPass)

        self.btn_cancelar = tk.Button(top)
        self.btn_cancelar.place(relx=0.59, rely=0.693, height=29, width=80)
        self.btn_cancelar.configure(activebackground="#f9f9f9")
        self.btn_cancelar.configure(text='''Cancelar''')
        self.btn_cancelar.configure(command = Cancel)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.590, rely=0.421, height=30, width=110)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#fff")
        self.Label2.configure(foreground="#ff0000")

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.394, rely=0.045, height=109, width=109)
        self.Label3.configure(background="#fff")
        photo_location = os.path.join(prog_location,"./rsz_1lock.gif")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label3.configure(image=_img0)
        self.Label3.configure(text='''Label''')

if __name__ == '__main__':
    vp_start_gui()





