#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Sep 27, 2020 10:12:31 AM CAT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    rsz_definicao_gif "./rsz_definicao.gif" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #fff -highlightbackground #fff -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 547x522+450+108
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Config"
    vTcl:DefineAlias "$top" "ToplevelSetting" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left \
        -text {Humidade do solo para rega} 
    vTcl:DefineAlias "$top.lab45" "lbl_config" vTcl:WidgetProc "ToplevelSetting" 1
    entry $top.ent46 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable hum_solo -width 196 
    vTcl:DefineAlias "$top.ent46" "edt_hum" vTcl:WidgetProc "ToplevelSetting" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image rsz_definicao_gif -text Label 
    vTcl:DefineAlias "$top.lab47" "Label1" vTcl:WidgetProc "ToplevelSetting" 1
    checkbutton $top.che48 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #fff -highlightcolor black -justify left \
        -state active -text {Rega por tempo} -variable che48 
    vTcl:DefineAlias "$top.che48" "Cbtn_using_time" vTcl:WidgetProc "ToplevelSetting" 1
    entry $top.ent49 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -state disabled -textvariable edt_tempo \
        -width 36 
    vTcl:DefineAlias "$top.ent49" "edt_tempo_hora" vTcl:WidgetProc "ToplevelSetting" 1
    button $top.but50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Salvar 
    vTcl:DefineAlias "$top.but50" "btn_save_config" vTcl:WidgetProc "ToplevelSetting" 1
    button $top.but51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command cancelarConfig \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Cancelar 
    vTcl:DefineAlias "$top.but51" "btn_cancelar" vTcl:WidgetProc "ToplevelSetting" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #fff -highlightcolor black -justify left \
        -state disabled -text {Tempos de rega} 
    vTcl:DefineAlias "$top.lab52" "Label2" vTcl:WidgetProc "ToplevelSetting" 1
    button $top.but55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -state disabled -text Adicionar -textvariable add_tempo 
    vTcl:DefineAlias "$top.but55" "btn_add" vTcl:WidgetProc "ToplevelSetting" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Desenvolvido por Cyber Z Moz} 
    vTcl:DefineAlias "$top.lab56" "Label3" vTcl:WidgetProc "ToplevelSetting" 1
    spinbox $top.spi45 \
        -activebackground #f9f9f9 -background white -font TkDefaultFont \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground blue -selectforeground white -textvariable sbox_val \
        -to 100.0 \
        -values {{Todas valvulas} {Valvula 1} {Valvula 2} {Valvula 3} {Valvula 4}} 
    vTcl:DefineAlias "$top.spi45" "sbox_valvulas" vTcl:WidgetProc "ToplevelSetting" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Valvulas por acionar} 
    vTcl:DefineAlias "$top.lab46" "Label4" vTcl:WidgetProc "ToplevelSetting" 1
    button $top.but47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command aplicarConfig \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Aplicar 
    vTcl:DefineAlias "$top.but47" "btn_aplicar_config" vTcl:WidgetProc "ToplevelSetting" 1
    entry $top.ent45 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -state disabled -width 36 
    vTcl:DefineAlias "$top.ent45" "edt_tempo_min" vTcl:WidgetProc "ToplevelSetting" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text : 
    vTcl:DefineAlias "$top.lab49" "Label6" vTcl:WidgetProc "ToplevelSetting" 1
    labelframe $top.lab51 \
        -font TkDefaultFont -foreground black -text {Dias de rega} \
        -background #fff -height 45 -highlightcolor black -width 430 
    vTcl:DefineAlias "$top.lab51" "Labelframe1" vTcl:WidgetProc "ToplevelSetting" 1
    set site_3_0 $top.lab51
    checkbutton $site_3_0.che55 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #fff -highlightcolor black -justify left \
        -text Seg -variable che55 
    vTcl:DefineAlias "$site_3_0.che55" "ckb_seg" vTcl:WidgetProc "ToplevelSetting" 1
    checkbutton $site_3_0.che56 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #fff -highlightcolor black -justify left \
        -text Ter -variable che56 
    vTcl:DefineAlias "$site_3_0.che56" "ckb_ter" vTcl:WidgetProc "ToplevelSetting" 1
    checkbutton $site_3_0.che57 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #fff -highlightcolor black -justify left \
        -text Qua -variable che57 
    vTcl:DefineAlias "$site_3_0.che57" "ckb_qua" vTcl:WidgetProc "ToplevelSetting" 1
    checkbutton $site_3_0.che58 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #fff -highlightcolor black -justify left \
        -text Qui -variable che58 
    vTcl:DefineAlias "$site_3_0.che58" "ckb_qui" vTcl:WidgetProc "ToplevelSetting" 1
    checkbutton $site_3_0.che59 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #fff -highlightcolor black -justify left \
        -text Sex -variable che59 
    vTcl:DefineAlias "$site_3_0.che59" "ckb_sex" vTcl:WidgetProc "ToplevelSetting" 1
    checkbutton $site_3_0.che61 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #fff -highlightcolor black -justify left \
        -text Sab -variable che61 
    vTcl:DefineAlias "$site_3_0.che61" "ckb_sab" vTcl:WidgetProc "ToplevelSetting" 1
    checkbutton $site_3_0.che63 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #fff -highlightcolor black -justify left \
        -text Dom -variable che63 
    vTcl:DefineAlias "$site_3_0.che63" "ckb_dom" vTcl:WidgetProc "ToplevelSetting" 1
    place $site_3_0.che55 \
        -in $site_3_0 -x 0 -relx 0.028 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.119 -height 0 -relheight 0.467 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che56 \
        -in $site_3_0 -x 0 -relx 0.163 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.093 -height 0 -relheight 0.467 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che57 \
        -in $site_3_0 -x 0 -relx 0.279 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.119 -height 0 -relheight 0.467 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che58 \
        -in $site_3_0 -x 0 -relx 0.419 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.1 -height 0 -relheight 0.467 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che59 \
        -in $site_3_0 -x 0 -relx 0.535 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.123 -height 0 -relheight 0.467 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che61 \
        -in $site_3_0 -x 0 -relx 0.651 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.123 -height 0 -relheight 0.467 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che63 \
        -in $site_3_0 -x 0 -relx 0.791 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.147 -height 0 -relheight 0.467 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx 0.272 -y 0 -rely 0.133 -width 0 -relwidth 0.484 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 0 -relx 0.347 -y 0 -rely 0.192 -width 196 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.037 -y 0 -rely 0.077 -width 0 -relwidth 0.221 \
        -height 0 -relheight 0.186 -anchor nw -bordermode ignore 
    place $top.che48 \
        -in $top -x 0 -relx 0.329 -y 0 -rely 0.498 -width 0 -relwidth 0.353 \
        -height 0 -relheight 0.071 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.274 -y 0 -rely 0.69 -width 36 -relwidth 0 \
        -height 41 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.247 -y 0 -rely 0.812 -height 29 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.444 -y 0 -rely 0.812 -height 29 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.219 -y 0 -rely 0.613 -width 0 -relwidth 0.484 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.512 -y 0 -rely 0.69 -width 69 -relwidth 0 \
        -height 39 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.296 -y 0 -rely 0.928 -width 0 -relwidth 0.484 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.spi45 \
        -in $top -x 0 -relx 0.293 -y 0 -rely 0.307 -width 0 -relwidth 0.488 \
        -height 0 -relheight 0.061 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.274 -y 0 -rely 0.249 -width 0 -relwidth 0.484 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.667 -y 0 -rely 0.812 -height 29 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 0 -relx 0.384 -y 0 -rely 0.69 -width 36 -relwidth 0 \
        -height 41 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.347 -y 0 -rely 0.709 -width 0 -relwidth 0.029 \
        -height 0 -relheight 0.036 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.11 -y 0 -rely 0.383 -width 0 -relwidth 0.786 \
        -height 0 -relheight 0.086 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

